# Generated by Django 3.2.9 on 2021-11-30 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0017_delete_favoritos'),
        ('outros', '0002_favoritos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritos',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto'),
        ),
    ]
