# Generated by Django 3.2.9 on 2021-12-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outros', '0003_alter_favoritos_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
