# Generated by Django 2.1.15 on 2021-11-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='nomesssss',
        ),
        migrations.AddField(
            model_name='categoria',
            name='nomes',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
