# Generated by Django 2.1.15 on 2021-11-03 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produtos', '0003_auto_20211103_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico_Produto',
            fields=[
                ('id_historico', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id_material', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('descricao', models.CharField(max_length=30)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=30)),
                ('descricao', models.TextField()),
                ('estoque_min', models.IntegerField()),
                ('estoque_max', models.IntegerField()),
                ('informacao_tec', models.TextField()),
                ('foto', models.TextField()),
                ('id_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Produto_Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('id_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.Material')),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.Produto')),
            ],
        ),
        migrations.CreateModel(
            name='Produto_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.Produto')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id_review', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('rating', models.IntegerField()),
                ('titulo', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=30)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Status_Produto',
            fields=[
                ('id_status_produto', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('descricao', models.CharField(max_length=20)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id_subcategoria', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=20)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id_tag', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('tag', models.CharField(max_length=20)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='nomes',
            new_name='nome',
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='id_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.Categoria'),
        ),
        migrations.AddField(
            model_name='produto_tag',
            name='id_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.Tag'),
        ),
        migrations.AddField(
            model_name='produto',
            name='id_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.Status_Produto'),
        ),
        migrations.AddField(
            model_name='produto',
            name='id_subcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.Subcategoria'),
        ),
        migrations.AddField(
            model_name='historico_produto',
            name='id_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.Produto'),
        ),
    ]
