# Generated by Django 2.1.15 on 2021-11-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_auto_20211103_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='variacaoproduto',
            name='nome',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
    ]
