# Generated by Django 2.1.15 on 2021-11-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_variacaoproduto_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='variacaoproduto',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
