# Generated by Django 2.1.15 on 2021-11-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_auto_20211105_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='variacaoproduto',
            name='foto',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cor',
            name='fotoCor',
            field=models.ImageField(upload_to='media'),
        ),
    ]
