# Generated by Django 2.1.15 on 2021-11-08 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0011_auto_20211108_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='fotosProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='produtos')),
            ],
        ),
        migrations.RemoveField(
            model_name='produto',
            name='foto2',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='foto3',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='foto4',
        ),
        migrations.AddField(
            model_name='fotosproduto',
            name='id_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.Produto'),
        ),
    ]
