# Generated by Django 2.1.15 on 2021-11-09 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0012_auto_20211108_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='foto',
        ),
    ]
