# Generated by Django 2.1.15 on 2021-11-19 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0013_remove_produto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='id_variacaoProduto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.VariacaoProduto', unique=True),
        ),
    ]
