# Generated by Django 2.1.15 on 2021-11-22 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0014_auto_20211119_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='id_variacaoProduto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='produtos.VariacaoProduto'),
        ),
    ]
