# Generated by Django 3.2.9 on 2021-11-30 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0016_favoritos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favoritos',
        ),
    ]
