# Generated by Django 3.2.9 on 2021-11-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0017_delete_favoritos'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='fotoPr',
            field=models.ImageField(null=True, upload_to='produtos'),
        ),
    ]
