# Generated by Django 3.2.9 on 2021-12-02 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0020_auto_20211202_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='descricao',
            field=models.TextField(max_length=1000),
        ),
    ]
