# Generated by Django 3.2.9 on 2022-03-21 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0022_auto_20220111_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotosproduto',
            name='foto',
        ),
    ]
