# Generated by Django 3.2.9 on 2022-03-21 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0023_remove_fotosproduto_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='fotoPr',
        ),
    ]
