# Generated by Django 3.2.9 on 2022-03-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0024_remove_produto_fotopr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variacaoproduto',
            name='foto',
            field=models.ImageField(upload_to=''),
        ),
    ]
