# Generated by Django 3.2.9 on 2022-03-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0025_alter_variacaoproduto_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotosproduto',
            name='foto',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
