# Generated by Django 2.1.15 on 2021-10-22 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211021_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco_cliente',
            fields=[
                ('id_endereco', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cep', models.CharField(max_length=10)),
                ('cidade', models.CharField(max_length=31)),
                ('rua', models.CharField(max_length=31)),
                ('numero', models.CharField(max_length=11)),
                ('bairro', models.CharField(max_length=31)),
                ('estado', models.CharField(max_length=31)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Telefone_cliente',
            fields=[
                ('id_telefone', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('tipo', models.CharField(choices=[['P', 'Principal'], ['S', 'Secundario']], default='S', max_length=1)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
