# Generated by Django 2.1.15 on 2021-10-26 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211022_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endereco_cliente',
            old_name='complememento2',
            new_name='complemento2',
        ),
    ]
