# Generated by Django 2.1.15 on 2021-11-17 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20211025_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telefone_cliente',
            name='tipo',
        ),
    ]
