# Generated by Django 3.2.9 on 2021-11-30 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupons',
            fields=[
                ('cupom', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('desconto', models.IntegerField()),
                ('max', models.IntegerField()),
            ],
        ),
    ]
