# Generated by Django 3.2.9 on 2021-11-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_cupons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_solicitacao',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
    ]
