# Generated by Django 3.2.9 on 2021-11-30 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_status_solicitacao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cupons',
        ),
        migrations.DeleteModel(
            name='Status_solicitacao',
        ),
        migrations.DeleteModel(
            name='Tipo_solicitacao',
        ),
    ]
