# Generated by Django 3.2.9 on 2021-11-25 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_frete'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='opcaofrete',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
