# Generated by Django 3.2.9 on 2021-11-26 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedido_opcaofrete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='preco',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='frete',
            field=models.FloatField(),
        ),
    ]
