# Generated by Django 3.2.9 on 2021-12-01 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_auto_20211125_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id_status', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Status', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pedidos.status'),
            preserve_default=False,
        ),
    ]
