# Generated by Django 3.2.9 on 2021-12-01 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_auto_20211201_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='status',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
