# Generated by Django 3.2.9 on 2021-12-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_auto_20211201_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='Status',
            field=models.CharField(max_length=50),
        ),
    ]
