# Generated by Django 3.2.9 on 2021-12-01 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_alter_status_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='status',
            new_name='status_pedido',
        ),
    ]
