# Generated by Django 3.2.9 on 2021-12-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='img',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='link',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='qr',
            field=models.TextField(null=True),
        ),
    ]
